units:
  kx: u
  ky: u
  px: 7
  py: 7

points:
  key.padding: ky
  zones:
    matrix:
      anchor:
        shift: [160, -160]
      columns:
        pinky:
          key:
            col_net: C0
            spread: kx
            stagger: 0
        ring:
          key:
            col_net: C1
            spread: kx
            stagger: 0.42 ky
        middle:
          key:
            col_net: C2
            spread: kx
            stagger: 0.28 ky
        index:
          key:
            col_net: C3
            spread: kx
            stagger: -0.17 ky
        inner:
          key:
            col_net: C4
            spread: kx
            stagger: -0.11 ky
      rows:
        top:
          row_net: R2
        home:
          row_net: R1
        bottom:
          row_net: R0

    thumbs:
      anchor:
        ref: matrix_inner_bottom
        shift: [-1.3kx, -2.95 ky]
      columns:
        inner:
          key:
            spread: kx
            splay: 0
            origin: [-0.5 kx, -0.5 ky]
            col_net: C2
        home:
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -0.5 ky]
            col_net: C3
        outter:
          key:
            spread: kx
            splay: -15
            origin: [-0.5 kx, -0.5 ky]
            col_net: C4
      rows:
        thumb:
          row_net: R3
          rotate: 90

outlines:
  keycap:
    - what: rectangle
      where: /matrix|thumbs/
      size: [kx - 1, ky - 1]

  switch_cutouts:
    - what: rectangle
      where: /matrix|thumbs/
      size: [14, 14]

  plate_cutout:
    - what: rectangle
      where: /matrix|thumbs/
      size: [kx + px, ky + py]
      fillet: 1
    - what: rectangle
      size: [30, 25]
      adjust:
        ref: matrix_pinky_bottom
        shift: [28.9, -44]
        rotate: -20
      fillet: 1
      operation: add

  mounting_holes:
    - what: circle
      where:
        ref: matrix_pinky_top
        shift: [9, 9.5]
      radius: 1.6
    - what: circle
      where:
        ref: matrix_pinky_bottom
        shift: [9, -9.5]
      radius: 1.6
    - what: circle
      where:
        ref: matrix_ring_top
        shift: [10, -16]
      radius: 1.6
    - what: circle
      where:
        ref: matrix_inner_bottom
        shift: [-10, -7.4]
      radius: 1.6
    - what: circle
      where:
        ref: thumbs_outter_thumb
        shift: [0, 11]
      radius: 1.6

  bottom:
    - what: outline
      name: plate_cutout
      operation: add
    - what: rectangle
      size: [23, 76]
      adjust:
        ref: matrix_inner_bottom
        shift: [22, -25]
      fillet: 1
      operation: add
    - what: outline
      name: mounting_holes
      operation: subtract

  plate:
    - what: outline
      name: plate_cutout
      operation: add
    - what: outline
      name: switch_cutouts
      operation: subtract
    - what: outline
      name: mounting_holes
      operation: subtract

  front:
    - what: outline
      name: plate_cutout
      operation: add
    - what: outline
      name: keycap
      operation: subtract

pcbs:
  collapse:
    template: kicad8
    outlines:
      edge:
        outline: bottom

    footprints:
      mx_switches:
        what: mx
        where: /matrix|thumbs/
        params:
          from: "{{col_net}}"
          to: "{{row_net}}"
          hotswap: false
          stabilizers: false
        adjust:
          rotate: -90

      diodes:
        what: diode
        where: /matrix|thumbs/
        adjust:
          shift: [-5, 0]
          rotate: 90
        params:
          from: "{{row_net}}"
          to: "{{row_net}}"
          pin_distance: 7.62
          smd: false

      switch_crossover:
        what: crossover
        where: /matrix/
        adjust:
          shift: [5, -5]
        params:
          from: "{{row_net}}"
          to: "{{row_net}}"

      encoder:
        what: rotary
        adjust:
          ref: matrix_inner_bottom
          shift: [23, -47]
          rotate: -120
        params:
          A: ENC_A
          B: ENC_B
          C: GND
          from: GND
          to: ENC_SWT
          legs: GND

      pro_micro:
        what: promicro
        where:
            ref: matrix_inner_bottom
            shift: [23, -6]
            rotate: -90
        params:
            RAW: RAW
            GND: GND
            RST: RST
            VCC: VCC
            P21: C0
            P20: C1
            P19: C2
            P18: C3
            P15: C4
            P14: R0
            P16: R1
            P10: R2
            P9:  R3
            P8:  ENC_A
            P7:  ENC_B
            P6:  ENC_SWT
            P2:  SDA
            P3:  SCL

      trrs:
        what: trrsbreakoutv3
        where:
            ref: matrix_inner_bottom
            shift: [23, -30]
        params:
            TIP: SCL
            R1:  SDA
            R2:  GND
            S:   VCC
            NC_T1: ENC_B
            NC_T2: ENC_A
            NC_B1: ENC_B
            NC_B2: ENC_A

      pullup_sda:
        what: resistor
        where:
            ref: matrix_inner_bottom
            shift: [23, -2]
        params:
            from: VCC
            to: SDA
            pin_distance: 8
            smd: false

      pullup_scl:
        what: resistor
        where:
            ref: matrix_inner_bottom
            shift: [23, -5]
        params:
            from: VCC
            to: SCL
            pin_distance: 8
            smd: false
